// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEYiNnqI44B84rZ87hpUCciYx0_yIZha0',
    appId: '1:1035919489788:web:a43ec6928c57c621fc3579',
    messagingSenderId: '1035919489788',
    projectId: 'pet-control-mqtt',
    authDomain: 'pet-control-mqtt.firebaseapp.com',
    storageBucket: 'pet-control-mqtt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS0UerL8AbxJCFwRKaIjro0jMP9BNHkqs',
    appId: '1:1035919489788:android:1acc2b826e646c48fc3579',
    messagingSenderId: '1035919489788',
    projectId: 'pet-control-mqtt',
    storageBucket: 'pet-control-mqtt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZBxtIKAIhfm7JyHqXGrbazQXdEtm6sdM',
    appId: '1:1035919489788:ios:31bb4efef104c271fc3579',
    messagingSenderId: '1035919489788',
    projectId: 'pet-control-mqtt',
    storageBucket: 'pet-control-mqtt.appspot.com',
    iosClientId: '1035919489788-ebaej3mbf7n019q5cch7iahdr0ll6vj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMqtt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZBxtIKAIhfm7JyHqXGrbazQXdEtm6sdM',
    appId: '1:1035919489788:ios:31bb4efef104c271fc3579',
    messagingSenderId: '1035919489788',
    projectId: 'pet-control-mqtt',
    storageBucket: 'pet-control-mqtt.appspot.com',
    iosClientId: '1035919489788-ebaej3mbf7n019q5cch7iahdr0ll6vj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMqtt',
  );
}
